[metadata]
name = "civitforge"
version = "2.1.3"
description = "CivitForge - federated Rust-native software forge for extreme-scale monorepos"
vendor = "CivitForge"
source = "https://github.com/WyattAu/CivitForge"
license = "AGPL-3.0-or-later"
tier = "critical"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "binary"
url = "https://github.com/WyattAu/CivitForge"

[runtime]
entrypoint = ["/etc/entrypoint.sh"]
cmd = []

[ports]
expose = [8080, 2222, 9090, 9101]

[labels]
"org.opencontainers.image.title" = "civitforge"
"org.opencontainers.image.vendor" = "CivitForge"
"org.opencontainers.image.version" = "2.1.3"
"org.opencontainers.image.source" = "https://github.com/WyattAu/CivitForge"
"org.opencontainers.image.description" = "CivitForge - federated Rust-native software forge for extreme-scale monorepos"
"org.opencontainers.image.licenses" = "AGPL-3.0-or-later"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.wolfi" = "true"
"evergreen.image.tier" = "critical"
"evergreen.health.type" = "http"
"evergreen.image.category" = "source-control"
"evergreen.image.status" = "functional"
