{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "civitforge.fullname" . }}
  labels:
    {{- include "civitforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
{{- end }}
