#![forbid(unsafe_code)]

pub mod api;
pub mod audit;
pub mod auth;
pub mod backup;
pub mod cache;
pub mod config;
pub mod db;
pub mod deploy_keys;
pub mod docs;
pub mod error;
pub mod event_queues;
pub mod events;
pub mod feature_flags;
pub mod federation;
pub mod git;
pub mod health;
pub mod ldap;
pub mod license_scanner;
pub mod loadtest;
pub mod merge_queue;
pub mod middleware;
pub mod mirror;
pub mod notifications;
pub mod performance;
pub mod policy;
pub mod protection;
pub mod provenance;
pub mod release;
pub mod release_manager;
pub mod runner;
pub mod scaling;
pub mod scheduler;
pub mod search;
pub mod secrets;
pub mod shutdown;
pub mod ssh;
pub mod storage;
pub mod telemetry;
pub mod vuln_scanner;
pub mod webhook;
pub mod webhooks;
pub mod wiki;

pub use config::AppConfig;
pub use db::{DatabasePool, DbRepository};
pub use error::{CoreError, Result};
pub use events::{Event, EventBus, EventCategory, EventPayload, EventSubscriber, EventPublisher, PublishedEvent, EventSubscription, WebSocketManager};
pub use ssh::{SshAuthService, SshConfig, SshServer};
