#![forbid(unsafe_code)]

pub mod shared_types;

pub mod api;
pub mod audit;
pub mod auth;
pub mod backup;
pub mod cache;
pub mod circuit_breaker;
pub mod chaos;
pub mod config;
pub mod db;
pub mod deploy_keys;
pub mod docs;
pub mod error;
pub mod event_queues;
pub mod events;
pub mod feature_flags;
pub mod federation;
pub mod git;
pub mod health;
pub mod ldap;
pub mod license_scanner;
pub mod loadtest;
pub mod merge_queue;
pub mod middleware;
pub mod mirror;
pub mod notifications;
pub mod performance;
pub mod policy;
pub mod protection;
pub mod realtime;
pub mod provenance;
pub mod release;
pub mod release_manager;
pub mod resilience;
pub mod runner;
pub mod scaling;
pub mod scheduler;
pub mod search;
pub mod secrets;
pub mod shutdown;
pub mod ssh;
pub mod storage;
pub mod telemetry;
pub mod vuln_scanner;
pub mod security_scanner;
pub mod security_scanner_v5;
pub mod security_scanner_v6;
pub mod security_scanner_v7;
pub mod security_scanner_v8;
pub mod security_scanner_v9;
pub mod security_scanner_v10;
pub mod security_scanner_v11;
pub mod security_scanner_v12;
pub mod security_scanner_v13;
pub mod security_scanner_v14;
pub mod security_scanner_v15;
pub mod security_scanner_v16;
pub mod security_scanner_v17;
pub mod security_scanner_v18;
pub mod security_scanner_v19;
pub mod security_scanner_v20;
pub mod security_scanner_v21;
pub mod security_scanner_v22;
pub mod security_scanner_v23;
pub mod security_scanner_v24;
pub mod compliance;
pub mod compliance_v3;
pub mod compliance_v4;
pub mod compliance_v5;
pub mod compliance_v6;
pub mod compliance_v7;
pub mod compliance_v10;
pub mod compliance_v11;
pub mod compliance_v12;
pub mod compliance_v13;
pub mod compliance_v14;
pub mod compliance_v15;
pub mod compliance_v16;
pub mod compliance_v17;
pub mod compliance_v18;
pub mod compliance_v19;
pub mod compliance_v20;
pub mod compliance_v21;
pub mod compliance_v22;
pub mod compliance_v23;
pub mod compliance_v24;
pub mod audit_trail;
pub mod audit_trail_v4;
pub mod audit_trail_v5;
pub mod audit_trail_v6;
pub mod audit_trail_v8;
pub mod audit_trail_v9;
pub mod audit_trail_v10;
pub mod audit_trail_v11;
pub mod audit_trail_v12;
pub mod audit_trail_v13;
pub mod audit_trail_v14;
pub mod audit_trail_v15;
pub mod audit_trail_v16;
pub mod audit_trail_v17;
pub mod audit_trail_v18;
pub mod audit_trail_v19;
pub mod audit_trail_v20;
pub mod audit_trail_v21;
pub mod audit_trail_v22;
pub mod audit_trail_v23;
pub mod audit_trail_v24;
pub mod deployment_strategy;
pub mod infrastructure;
pub mod service_mesh;
pub mod test_coverage;
pub mod code_quality;
pub mod performance_testing;
pub mod data_archival;
pub mod data_migration;
pub mod network_policy;
pub mod encryption;
pub mod acl;
pub mod workflow_engine;
pub mod automation_rules;
pub mod scheduled_tasks;
pub mod log_aggregation;
pub mod log_aggregation_v22;
pub mod log_aggregation_v23;
pub mod distributed_tracing_v2;
pub mod distributed_tracing_v23;
pub mod distributed_tracing_v24;
pub mod dashboard_reporting;
pub mod dashboard_reporting_v22;
pub mod dashboard_reporting_v23;
pub mod pipeline_secrets_v2;
pub mod pipeline_runners_v2;
pub mod environment_variables;
pub mod test_suite_management;
pub mod review_automation;
pub mod quality_gates;
pub mod firewall;
pub mod intrusion_detection;
pub mod ddos_protection;
pub mod object_storage;
pub mod backup_encryption;
pub mod data_retention;
pub mod database_replication_v2;
pub mod database_replication_v3;
pub mod database_replication_v4;
pub mod database_replication_v5;
pub mod database_replication_v7;
pub mod database_replication_v8;
pub mod database_replication_v9;
pub mod database_replication_v11;
pub mod database_replication_v12;
pub mod database_replication_v14;
pub mod database_replication_v15;
pub mod database_replication_v16;
pub mod database_replication_v17;
pub mod database_replication_v18;
pub mod database_replication_v19;
pub mod database_replication_v20;
pub mod database_replication_v21;
pub mod database_replication_v22;
pub mod encryption_v3;
pub mod encryption_v4;
pub mod encryption_v5;
pub mod encryption_v6;
pub mod encryption_v8;
pub mod encryption_v9;
pub mod encryption_v10;
pub mod encryption_v12;
pub mod encryption_v13;
pub mod encryption_v15;
pub mod encryption_v16;
pub mod encryption_v17;
pub mod encryption_v18;
pub mod encryption_v19;
pub mod encryption_v20;
pub mod encryption_v21;
pub mod encryption_v22;
pub mod encryption_v23;
pub mod data_residency_v2;
pub mod data_residency_v3;
pub mod data_residency_v4;
pub mod data_residency_v5;
pub mod data_residency_v7;
pub mod data_residency_v8;
pub mod data_residency_v9;
pub mod data_residency_v11;
pub mod data_residency_v12;
pub mod data_residency_v14;
pub mod data_residency_v15;
pub mod data_residency_v16;
pub mod data_residency_v17;
pub mod data_residency_v18;
pub mod data_residency_v19;
pub mod data_residency_v20;
pub mod data_residency_v21;
pub mod data_residency_v22;
pub mod pipeline_action_reviews_v3;
pub mod pipeline_action_reviews_v5;
pub mod pipeline_action_reviews_v6;
pub mod pipeline_action_reviews_v8;
pub mod pipeline_action_reviews_v9;
pub mod pipeline_action_reviews_v10;
pub mod pipeline_action_reviews_v11;
pub mod pipeline_action_reviews_v12;
pub mod pipeline_action_reviews_v13;
pub mod pipeline_action_reviews_v14;
pub mod pipeline_action_reviews_v16;
pub mod environment_deployment_v3;
pub mod environment_deployment_v5;
pub mod environment_deployment_v6;
pub mod environment_deployment_v8;
pub mod environment_deployment_v9;
pub mod environment_deployment_v10;
pub mod environment_deployment_v11;
pub mod environment_deployment_v12;
pub mod environment_deployment_v13;
pub mod environment_deployment_v14;
pub mod environment_deployment_v16;
pub mod cache_hit_analysis_v2;
pub mod cache_hit_analysis_v3;
pub mod cache_hit_analysis_v5;
pub mod cache_hit_analysis_v7;
pub mod cache_hit_analysis_v8;
pub mod cache_hit_analysis_v9;
pub mod cache_hit_analysis_v10;
pub mod cache_hit_analysis_v11;
pub mod cache_hit_analysis_v12;
pub mod cache_hit_analysis_v13;
pub mod cache_hit_analysis_v15;
pub mod pipeline_action_reviews_v17;
pub mod environment_deployment_v17;
pub mod cache_hit_analysis_v16;
pub mod pipeline_action_reviews_v18;
pub mod environment_deployment_v18;
pub mod cache_hit_analysis_v17;

pub use telemetry::apm::{ApmConfig, ApmRecorder, ApmTransaction, ApmSpan, ApmDashboard, TransactionStats};
pub use telemetry::distributed_tracing::{
    DistributedTracer, DistributedTracingConfig, TraceSpan, TraceEvent,
    TRACEPARENT_HEADER, TRACESTATE_HEADER,
    parse_traceparent, format_traceparent, generate_trace_id, generate_span_id,
};
pub use telemetry::error_tracking::{ErrorTracker, ErrorTrackingConfig, ErrorRecord, ErrorSummary};
pub mod webhook;
pub mod webhooks;
pub mod wiki;

pub use config::AppConfig;
pub use db::{DatabasePool, DbRepository};
pub use error::{CoreError, Result};
pub use events::{Event, EventBus, EventCategory, EventPayload, EventSubscriber, EventPublisher, PublishedEvent, EventSubscription, WebSocketManager};
pub use ssh::{SshAuthService, SshConfig, SshServer};

#[cfg(test)]
mod workflow_engine_tests;
#[cfg(test)]
mod automation_rules_tests;
#[cfg(test)]
mod security_scanner_tests;
#[cfg(test)]
mod compliance_tests;
#[cfg(test)]
mod audit_trail_tests;
